package model.modifiers;

public enum Seal {
    RED_SEAL, // RETRIGGER THE CARD ONCE
    BLUE_SEAL, // GENERATES A PLANET CARD CORRESPONDING TO THE LAST PLAYED HAND TYPE AT END OF ROUND
    GOLD_SEAL, // EARNS 3$ WHEN PLAYED
    GREEN_SEAL // DISCARDING THE CARD GENERATES A TAROT CARD
}
